### ISSUE TITLE
Class 'WCVendors_Pro_Vendor_Controller' not found in /wc-vendors/classes/admin/class-admin-users.php:515

### ISSUE THREAD

**Issue by yannbug** [wcvendors/wcvendors#571]
Steps to reproduce:

- Install latest version of WC-Vendors Free (2.1.10)
- Go to /wp-admin/users.php (users list in the admin)
- Filter on vendors

![Capture du 2019-06-13 17-05-21](https://user-images.githubusercontent.com/3611997/59444109-8f2f6100-8dfd-11e9-9729-3829fed048fa.png)

Error details:
~~~
Une erreur de type E_ERROR a été causée dans la ligne 515 du fichier /home/www/wc.celyan.com/wp-content/plugins/wc-vendors/classes/admin/class-admin-users.php. Message d’erreur : Uncaught Error: Class 'WCVendors_Pro_Vendor_Controller' not found in /home/www/wc.celyan.com/wp-content/plugins/wc-vendors/classes/admin/class-admin-users.php:515
Stack trace:
#0 /home/www/wc.celyan.com/wp-includes/class-wp-hook.php(286): WCV_Admin_Users->add_vendor_shop_column_data('', 'vendor', 249)
#1 /home/www/wc.celyan.com/wp-includes/plugin.php(208): WP_Hook->apply_filters('', Array)
#2 /home/www/wc.celyan.com/wp-admin/includes/class-wp-users-list-table.php(543): apply_filters('manage_users_cu...', '', 'vendor', 249)
#3 /home/www/wc.celyan.com/wp-admin/includes/class-wp-users-list-table.php(375): WP_Users_List_Table->single_row(Object(WP_User), '', '', 0)
#4 /home/www/wc.celyan.com/wp-admin/includes/class-wp-list-table.php(1244): WP_Users_List_Table->display_rows()
#5 /home/www/wc.celyan.com/wp-admin/includes/class-wp-list-table.php(1175): WP_List_Table->display_rows_or_placeholder()
#6 /home/www/wc.celyan.com/wp-admin/users.php(578): WP_List_Table->display()
#7 {main}
  thrown

**Comment by yannbug** [comment]
fixed by 2.1.11
