### ISSUE TITLE
Call to a member function get_id() on boolean

### ISSUE THREAD

**Issue by olegabr** [wcvendors/wcvendors#745]
Sorry for not following bug report template, just found this in the fatal-errors log on my customer's site today:

```
2021-03-28T17:10:08+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on boolean in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wc-vendors/classes/admin/class-wcv-commissions-page.php:117
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/class-wp-list-table.php(1447): WCVendors_Commissions_Page->column_default(Object(stdClass), 'shipped')
#1 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/class-wp-list-table.php(1387): WP_List_Table->single_row_columns(Object(stdClass))
#2 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/class-wp-list-table.php(1374): WP_List_Table->single_row(Object(stdClass))
#3 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/class-wp-list-table.php(1359): WP_List_Table->display_rows()
#4 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/class-wp-list-table.php(1286): WP_List_Table->display_rows_or_placeholder()
#5 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wc-vendors/classes/admin/views/html-admin-commission-page.php(33): WP_List_Table->display()
#6 /o in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wc-vendors/classes/admin/class-wcv-commissions-page.php on line 117
```

PHP version: 7.2.16
WordPress version: 5.7
WooCommerce version: 5.1.0

Hope it can be useful.

## Proposed Solution ##

- [ ] Add extra check in commissions page output to ensure that the order exists before proceeding.

**Comment by digitalchild** [comment]
Hi @olegabr 

Has the user deleted any orders?

**Comment by olegabr** [comment]
yes, some orders were deleted

**Comment by digitalchild** [comment]
Hi @olegabr 

Ok, the commissions for those orders will need to be manually removed for now. I will also add another check in our code for if the order doesn't exist, not to proceed with this commission.

**Comment by olegabr** [comment]
@digitalchild Thank you!
